#!/bin/bash

declare -a cydia
cydia=($CYDIA)

rm -f /Library/MobileSubstrate/DynamicLibraries/locationModifierTweak.dylib
rm -f /Library/MobileSubstrate/DynamicLibraries/locationModifierTweak.plist

if [[ ${CYDIA+@} ]]; then
eval "echo 'finish:reload' >&${cydia[0]}"
else
echo "Haha, Please respring your device."
fi

exit 0

