include theos/makefiles/common.mk

TWEAK_NAME = locationModifierTweak
locationModifierTweak_FILES = Tweak.xm	MyLocationManagerDelegate.m
locationModifierTweak_FRAMEWORKS = UIKit	CoreLocation

include $(THEOS_MAKE_PATH)/tweak.mk
