#!/bin/bash

declare -a cydia
cydia=($CYDIA)

mv -f /Applications/GPSRocket.app/locationModifierTweak.dylib /Library/MobileSubstrate/DynamicLibraries/
mv -f /Applications/GPSRocket.app/locationModifierTweak.plist /Library/MobileSubstrate/DynamicLibraries/

if [[ ${CYDIA+@} ]]; then
eval "echo 'finish:reload' >&${cydia[0]}"
else
echo "Haha, Please respring your device MANYALLY."
fi

exit 0



